### ISSUE TITLE
Please remove fonts

### ISSUE THREAD

**Issue by mrecord** [melbandit/FinalProject_AS#1]
Hi Melissa, 
My name is Mark and I work at Commercial Type.
I noticed that there are several Graphik fonts posted to this repository.
The license for the fonts does not allow for the fonts to be shared online. Can you please remove them?
Thank you,
Mark

**Comment by melbandit** [comment]
Of course, I apologize. I will do this remove this today. Do you know where I can purchase the font so I can use it online?

Sincerely,
Melissa
